namespace VdlV.ValueTypes {
    /// <summary>
    /// The jobs that are needed at businesses, i.e. LocationTypes that need employees.
    /// The table that relates each Vocation to its LocationType(s) is _vocationLocations (see StaticTables).
    /// The table that assigns each Vocation a number of positions to fill per location is PositionsPerJob (see StaticTables).
    /// </summary>
    public enum Vocation {
        Architect,
        Baker,
        BankTeller,
        Barber,
        Barkeeper,
        Bartender,
        Bottler,
        Brewer,
        Builder,
        BusDriver,
        Busser,
        Butcher,
        Carpenter,
        Cashier,
        Clothier,
        Cook,
        Cooper,
        DaycareProvider,
        Dentist,
        Dishwasher,
        Distiller,
        Doctor,
        Dressmaker,
        Farmer,
        Farmhand,
        FireChief,
        Firefighter,
        Grocer,
        Groundskeeper,
        Innkeeper,
        Janitor,
        Jeweler,
        Joiner,
        Laborer,
        Maid,
        Mayor,
        Milkman,
        Millworker,
        Mortician,
        Nurse,
        Optometrist,
        Painter,
        Pharmacist,
        Plumber,
        PoliceChief,
        PoliceOfficer,
        PostalWorker,
        Principal,
        Puddler,
        Quarryman,
        Seamstress,
        Secretary,
        Shoemaker,
        Stocker,
        Stonecutter,
        Surgeon,
        Tailor,
        TattooArtist,
        Teacher,
        Turner,
        Waiter,
        Woodworker
    }
}
