namespace TotT.ValueTypes {
    /// <summary>
    /// The facets of personality. Uses the Dwarf Fortress 50.
    /// </summary>
    public enum Facet {
        AbstractInclined,
        ActivityLevel,
        Altruism,
        Ambition,
        AngerPropensity,
        AnxietyPropensity,
        ArtInclined,
        Assertiveness,
        Bashful,
        Bravery,
        CheerPropensity,
        Closeminded,
        Confidence,
        Cruelty,
        Curious,
        DepressionPropensity,
        Discord,
        DisdainAdvice,
        Dutifulness,
        EmotionallyObsessive,
        EnvyPropensity,
        ExcitementSeeking,
        Friendliness,
        Gratitude,
        Greed,
        Gregarioiusness,
        HatePropensity,
        Hopeful,
        Humor,
        Imagination,
        Immoderation,
        Immodesty,
        LovePropensity,
        LustPropensity,
        Orderliness,
        Perfectionist,
        Perseverance,
        Politeness,
        Pride,
        Privacy,
        Singleminded,
        StressVulnerability,
        SwayedByEmotions,
        Thoughtlessness,
        Tolerant,
        Trust,
        Vanity,
        Vengeful,
        Violent,
        Wastefulness
    }
}
